apiVersion: v1
kind: Secret
metadata:
  namespace: chatbot-ui
  name: chatbot-ui-secret
type: Opaque
stringData:
  OPENAI_API_KEY: c2stcHJvai1RblE0VVBpQjhnVGxQRXRJNVViNVQzQmxia0ZKYVIxMDVvbWFtY0JtRVJqb29weFU

# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
      - name: chatbot-ui
        image: <docker user>/chatbot-ui:latest
        resources: {}
        ports:
        - containerPort: 3000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-ui-secret  # Reference the secret name
              key: OPENAI_API_KEY
---

# Service definition (assuming it remains unchanged)
kind: Service
apiVersion: v1
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: chatbot-ui
  type: ClusterIP
